name: Automated Essay Scoring Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm

    - name: Run main.py
      run: |
        python main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: output_files
        path: |
          models/best_model.joblib
          submission.csv